inherit_from: .rubocop_todo.yml
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 130  
Style/ClassAndModuleChildren:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
