default: &default
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['DATABASE_NAME']  || 'development' %>
  pool: 5
  username: <%= ENV['DATABASE_NAME']  || 'postgres' %>
  password: <%= ENV['DATABASE_NAME']  || '123' %>
  host: <%= ENV['DATABASE_HOST']  || 'localhost' %>

development:
  <<: *default

test:
  <<: *default
  database: test_db
production:
  <<: *default  
